// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Story struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Online int      `json:"online"`
	People int      `json:"people"`
	Tags   []string `json:"tags"`
	Turns  []*Turn  `json:"turns"`
}

type StoryInput struct {
	Name string   `json:"name"`
	Tags []string `json:"tags"`
}

type Turn struct {
	ID    int    `json:"id"`
	User  *User  `json:"user"`
	Value string `json:"value"`
}

type TurnInput struct {
	User  int    `json:"user"`
	Value string `json:"value"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
