// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type StoryInput struct {
	Name string `json:"name"`
	Tags string `json:"tags"`
}

type TurnInput struct {
	UserID  int    `json:"userID"`
	StoryID int    `json:"storyID"`
	Value   string `json:"value"`
}
